add_newline = true
command_timeout = 1000
"$schema" = 'https://starship.rs/config-schema.json'

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$ruby\
$docker_context\
$conda\
$pixi\
$time\
$line_break$character"""

[os]
disabled = false
style = "bg:red fg:white bold"
format = '[](fg:red)[$symbol]($style)'

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:red fg:white bold"
style_root = "bg:red fg:white bold"
format = '[ $user]($style)'

[hostname]
ssh_only = false
style = "bg:red fg:white bold"
format = '[@$hostname ]($style)'
trim_at = "."

# [shell]
# disabled = false
# style = "fg:red"
# format = '[ $indicator]($style)'
# bash_indicator = " "
# zsh_indicator = " "
# fish_indicator = "󰈺 "
# powershell_indicator = " "
# cmd_indicator = " "
# unknown_indicator = ""

[directory]
style = "bg:blue fg:white"
format = '[](fg:red bg:blue)[ $read_only$path ]($style)'
read_only = " "
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:yellow fg:black"
format = '[](fg:blue bg:yellow)[ $symbol $branch ]($style)'

[git_status]
style = "bg:yellow fg:black"
format = '[($all_status$ahead_behind )]($style)'
conflicted = " "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = " ${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[git_metrics]
disabled = true

[nodejs]
symbol = ""
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

[cpp]
symbol = " "
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

[java]
symbol = ""
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version)( \($virtualenv\)) ]($style)'

[ruby]
symbol = ""
style = "bg:bright-blue fg:white bold"
format = '[](fg:yellow bg:bright-blue)[ $symbol( $version) ]($style)'

# [package]
# symbol = "󰏗"
# style = "fg:green"
# display_private = true
# format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
style = "bg:cyan fg:black"
format = '[](fg:bright-blue bg:cyan)[ $symbol( $context) ]($style)'

[conda]
style = "bg:cyan fg:black"
format = '[](fg:bright-blue bg:cyan)[ $symbol( $environment) ]($style)'

[pixi]
style = "bg:cyan fg:black"
format = '[](fg:bright-blue bg:cyan)[ $symbol( $version)( $environment) ]($style)'

# [memory_usage]
# disabled = false
# symbol = "󰍛 "
# threshold = 0
# style = "bg:lavender fg:surface0"
# format = '[ $symbol${ram_pct} ]($style)'

[time]
disabled = false
time_format = "%R"
style = "bg:green fg:black"
format = '[](fg:cyan bg:green)[  $time ]($style)[](fg:green)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[ ❯ ](bg:green fg:black bold)'
error_symbol = '[ ❯ ](bg:red fg:white bold)'
vimcmd_symbol = '[ ❯ ](bg:green fg:black bold)'
vimcmd_replace_one_symbol = '[ ❯ ](bg:magenta fg:white bold)'
vimcmd_replace_symbol = '[ ❯ ](bg:magenta fg:white bold)'
vimcmd_visual_symbol = '[ ❯ ](bg:yellow fg:black bold)'

# [custom.cpu_load]
# disabled = false
# description = "CPU Load Average (1min)"
# command = "cat /proc/loadavg | awk '{print $1}'"
# when = "true"
# symbol = " "
# style = "bg:lavender fg:surface0"
# format = '[ $symbol$output ]($style)'
