add_newline = true
command_timeout = 1000
"$schema" = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_mocha'

format = """
$os\
$username\
$hostname\
$directory\
$git_branch\
$git_status\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
$ruby\
$docker_context\
$conda\
$pixi\
$time\
$line_break$character"""

[os]
disabled = false
style = "fg:red"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "fg:red bold"
style_root = "fg:red bold"
format = '[ $user]($style)'

[hostname]
ssh_only = false
style = "fg:red bold"
format = '[@$hostname ]($style)'
trim_at = "."

# [shell]
# disabled = false
# style = "fg:red"
# format = '[ $indicator]($style)'
# bash_indicator = " "
# zsh_indicator = " "
# fish_indicator = "󰈺 "
# powershell_indicator = " "
# cmd_indicator = " "
# unknown_indicator = ""

[directory]
style = "fg:peach"
format = "[$read_only$path ]($style)"
read_only = " "
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"~" = " "
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "
"dev" = "󰲋 "
"Desktop" = " "
"work" = " "
".config" = " "

[git_branch]
symbol = ""
style = "fg:yellow"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:yellow"
format = '[($all_status$ahead_behind )]($style)'
conflicted = " "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕⇡${ahead_count}⇣${behind_count} "
untracked = "?${count} "
stashed = " ${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "✘${count} "

[git_metrics]
disabled = false
added_style = "fg:green"
deleted_style = "fg:red"
format = '[+$added]($added_style)/[-$deleted]($deleted_style) '

[nodejs]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[c]
symbol = " "
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[cpp]
symbol = " "
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[rust]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[golang]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[php]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[java]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[kotlin]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[haskell]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

[python]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version)( \($virtualenv\)) ]($style)'

[ruby]
symbol = ""
style = "fg:green"
format = '[ $symbol( $version) ]($style)'

# [package]
# symbol = "󰏗"
# style = "fg:green"
# display_private = true
# format = '[ $symbol( $version) ]($style)'

[docker_context]
symbol = ""
style = "fg:sapphire"
format = '[ $symbol( $context) ]($style)'

[conda]
style = "fg:sapphire"
format = '[ $symbol( $environment) ]($style)'

[pixi]
style = "fg:sapphire"
format = '[ $symbol( $version)( $environment) ]($style)'

# [memory_usage]
# disabled = false
# symbol = "󰍛 "
# threshold = 0
# style = "bg:lavender fg:surface0"
# format = '[ $symbol${ram_pct} ]($style)'

[time]
disabled = false
time_format = "%R"
style = "fg:lavender"
format = '[  $time ]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[❯](bold green)'
error_symbol = '[❯](bold red)'
vimcmd_symbol = '[❯](bold green)'
vimcmd_replace_one_symbol = '[❯](bold magenta)'
vimcmd_replace_symbol = '[❯](bold magenta)'
vimcmd_visual_symbol = '[❯](bold yellow)'

# [custom.cpu_load]
# disabled = false
# description = "CPU Load Average (1min)"
# command = "cat /proc/loadavg | awk '{print $1}'"
# when = "true"
# symbol = " "
# style = "bg:lavender fg:surface0"
# format = '[ $symbol$output ]($style)'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
